### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by chr0m1ng** [zerobounce/zero-bounce-javascript#6]
I'm running an express server in node.js with Node version `v.18.13.0` and when I try to use this SDK I get the following error:

```
Error: TypeError: fetch failed
    at a (/Users/x/y/node_modules/@zerobounce/zero-bounce-sdk/dist/zeroBounceSDK.js:1:1292)
    at async /Users/x/y/dist/zero.js:9:26
```

I think you guys are missing a `node-fetch` import in your `utils.js` file when creating the request. If I simply add `const fetch = require('node-fetch');` to `zeroBounceSDK.js` inside my `node_modules` file it starts to work.

**Comment by vlungusst** [comment]
Can you provide a minimal example project for this as we're unable to reproduce this?
